# Uncomment this line to define a global platform for your project
	platform :ios, '9.0'

target 'GoChat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	

	pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'JSQMessagesViewController'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SDWebImage'
	
  # Pods for GoChat

  target 'GoChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
